config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :homes, only: [:index]
  resources :addresses, only: [:index]
  resources :qiitas, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postal_code.rb
class PostalCode
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :number, :integer
end

app/models/qiita_item.rb
require 'json'

class QiitaItem
  def self.get_response
    url = 'https://qiita.com'
    connection = Faraday.new(url: url)
    binding.pry
    response = connection.get do |req|
      req.url '/api/v2/items', page: 1, per_page: 100, query: 'tag:Rails updated:>2019-02 stocks:>3'
    end

    # QiitaのAPIから返ってきたJSONをパース
    json = JSON.parse(response.body)
    # 記事を一旦いいね数の降順でソートして記事タイトル／URL／いいね数のハッシュ形式にしたものを新しい配列をmapメソッドで生成
    json.sort_by { |i| i['likes_count']}.reverse.map do |item|
      { title: item['title'], url: item['url'], likes_count: item['likes_count'] }
    end.take(20)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    # hash形式でパラメタ文字列を指定し、URL形式にエンコード
    params = URI.encode_www_form({zipcode: get_params})
    # URIを解析し、hostやportをバラバラに取得できるようにする
    uri = URI.parse("http://zipcloud.ibsnet.co.jp/api/search?#{params}")
    # リクエストパラメタを、インスタンス変数に格納
    @query = uri.query

    # [GETリクエスト]
    # Net::HTTP.startで新しくHTTPセッションを開始し、結果をresponseへ格納
    # 既にセッションが開始している場合はIOErrorが発生
    response = Net::HTTP.start(uri.host, uri.port) do |http|
      # 接続時に待つ最大秒数を設定
      # タイムアウト時はTimeoutError例外が発生
      http.open_timeout = 5
      # 読み込み一回でブロックして良い最大秒数を設定
      # デフォルトは60秒
      # タイムアウト時はTimeoutError例外が発生
      http.read_timeout = 10
      # ここでWebAPIを叩いている
      # Net::HTTPResponseのインスタンスが返ってくる
      http.get(uri.request_uri)
    end
    # 例外処理の開始
    begin
      # responseの値に応じて処理を分ける
      case response
      # 成功した場合
      when Net::HTTPSuccess
        # [JSONパース処理]
        # responseのbody要素をJSON形式で解釈し、hashに変換
        # JSON::ParserErrorが発生する可能性がある
        @result = JSON.parse(response.body)
        # 表示用の変数に結果を格納
        @zipcode = @result["results"][0]["zipcode"]
        @address1 = @result["results"][0]["address1"]
        @address2 = @result["results"][0]["address2"]
        @address3 = @result["results"][0]["address3"]
      # 別のURLに飛ばされた場合
      when Net::HTTPRedirection
        @message = "Redirection: code=#{response.code} message=#{response.message}"
      # その他エラー
      else
        @message = "HTTP ERROR: code=#{response.code} message=#{response.message}"
      end
    # エラー時処理
    rescue IOError => e
      @message = "e.message"
    rescue TimeoutError => e
      @message = "e.message"
    rescue JSON::ParserError => e
      @message = "e.message"
    rescue => e
      @message = "e.message"
    end
  end


  private

  def get_params
    params.require(:postal_code)[:number]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @postal_code = PostalCode.new
  end

end

app/controllers/qiitas_controller.rb
class QiitasController < ApplicationController

  def index
    @items = QiitaItem.get_response
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/qiitas_helper.rb
module QiitasHelper
end

app/views/addresses/index.html.haml
%p 郵便番号:
= @zipcode
%p 都道府県:
= @address1
%p 市区町村:
= @address2
%p 町名:
= @address3
%p
-# リクエストパラメタを表示
リクエストパラメタ:
= @query
-# 生のjsonを表示
result:
= @result
%p
-# エラーメッセージを表示
message:
= @message

app/views/homes/index.html.haml
%p 郵便番号検索API(zipcloud)
= form_with(model: @postal_code, url: addresses_path, method: :get, local: true) do |f|
  = f.text_field :number, class:"postal-code-search__field", placeholder: "7桁/ハイフン無し"
  = f.submit "検索する"

%p Qiita
%button
  = link_to "Go", qiitas_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ApiAttacker
    = csrf_meta_tags
    = csp_meta_tag
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/qiitas/index.html.haml
= @items.each do |item|
  item[:title]
-# %h1 Rails記事一覧
-# %ol
-#   = @items.each do |item|
-#     %li
-#       = link_to item[:title], item[:url], target: '_blank'
-#       (item[:likes_count]いいね)